ekf_localization:
  ros__parameters:
    use_nonholonomic_constraint: false
    var_nhc_lateral_velocity: 0.05
    var_nhc_vertical_velocity: 0.02
    use_zupt: false
    use_zihr: false
    use_flat_ground: false
    var_zupt_velocity: 0.01
    var_zihr_gyro: 0.00001
    initial_imu_gyro_bias_covariance: 0.01
    use_continuous_process_noise_density: false
    use_second_order_state_transition: false
    use_second_order_process_noise: false
    propagation_model: "fast"
    enable_measurement_replay: true
    measurement_history_duration_sec: 0.6
    max_future_measurement_wait_sec: 5.0
    input_reorder_window_sec: 0.0
    compensate_gnss_delay: false
    gnss_position_robust_loss: "huber"
    gnss_position_robust_tuning: 2.5
    max_gnss_position_robust_variance_scale: 100.0
    gnss_navsatfix_use_position_covariance: true
    enable_fixed_lag_smoothing: true
    fixed_lag_duration_sec: 5.0
    fixed_lag_node_subsample: 10
